### ISSUE TITLE
Social icons footer

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#107]
Can we change the social icons in the footer to white. It don't have contrast with the background.
![image.png](https://images.zenhubusercontent.com/64d100d037a41802ee2a6fe8/9f563dbf-e331-4599-acd8-2f3508bfc650)

**Comment by LautaroPetaccio** [comment]
I'm tagging it as enhancement due to the footer having the same styles in all pages.

**Comment by LautaroPetaccio** [comment]
Closing it as we won't fix it.
