### ISSUE TITLE
Things are not refreshing in dApps as I've seen them do elsewhere in the world

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#108]
- For example in dApps I have pants
![image.png](https://images.zenhubusercontent.com/64d100d037a41802ee2a6fe8/fce50edf-47b1-4717-977e-8ce434fd7c7d)

-In world I don't have it
![image.png](https://images.zenhubusercontent.com/64d100d037a41802ee2a6fe8/254cd425-6c09-4558-af3c-cf5d2f850f8f)

Other thing is the description. I change it a few times and it doesn't works and I refresh each tab a few times.
- In dApps
![image.png](https://images.zenhubusercontent.com/64d100d037a41802ee2a6fe8/fa48929f-b923-4ed5-84a2-2150f13c0854)

-In world
![image.png](https://images.zenhubusercontent.com/64d100d037a41802ee2a6fe8/6b69893d-97e6-47dc-a2e4-e8763aab9166)

**Comment by LautaroPetaccio** [comment]
Hi Miki! I'm not sure if you remember, but we talked about these changes and how the Profile site wouldn't be aware of what was happening in other sites.
The only way to have a "work-around" is to continuously ask for the user's profile, but that can be a bit complex to do. I'll leave it as an enhancement.

**Comment by decentralandmiguel** [comment]
But Im refreshing the page and nothing happened too. That I expected it was only when the user don't refresh that we can't update it.

**Comment by LautaroPetaccio** [comment]
Closing this as it was an error of the explorer.
