### ISSUE TITLE
Mutual friends in public profile

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#118]
Why we show mutual friends if the user don't have mutuals with my profile? The best way is to avoid showing it.

Other thing is that mutual don't have icon, we have to add it.
![image.png](https://images.zenhubusercontent.com/64d100d037a41802ee2a6fe8/5842344c-9a87-48fa-9109-ad1dea840991)

**Comment by LautaroPetaccio** [comment]
Hi Miki! The mutuals section doesn't have an Icon in the designs, as the mutual friends are shown using the profile image of the mutual friends. When you don't have mutuals, there's no profile picture to show.
We can remove the mutuals component when there's no mutual.

**Comment by decentralandmiguel** [comment]
The component that we are proposing is this one where we show the first 3 mutual that the user have in common. I think this is very difficult, but if not we can use the Icon with 2 people 
<img width="603" alt="image" src="https://github.com/decentraland/profile/assets/138145487/680ce25e-f49b-4ed9-b13a-78cf4ec627b3">

**Comment by LautaroPetaccio** [comment]
Hi again Miki! We do have the icons with multiple users! If you have any mutual friend, it will grab the profile image of those friends and show it to you:
![Screenshot 2023-08-07 at 17.45.33.png](https://images.zenhubusercontent.com/60d9e2eae14d1d56b7547674/bfc495fa-3a3f-465a-b99c-6034e14484a1)
If you don't have any mutuals, it doesn't have anything to show.
We'll remove the mutuals section from the site when there are no mutual friends.
