### ISSUE TITLE
Avatar drag error

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#121]
I can drag the avatar out of the page.
https://images.zenhubusercontent.com/660762354/ee779a93-de92-49ff-91c0-a424eaf2c836/screen_recording_2023_08_07_at_17_18_40.mov

**Comment by LautaroPetaccio** [comment]
I can't reproduce it, are you able to reproduce it Miki?

**Comment by decentralandmiguel** [comment]
Yes I tried again now and I reproudce it again. If not we can huddle and I will show you.
