### ISSUE TITLE
View more button

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#122]
- 3 dots in normal status have to be white and have to be 0.5 px more separate.
- Also the on click behaviour it don't function very well. When I go out of the button it becomes white and viceversa.
https://images.zenhubusercontent.com/660762354/f46a750c-25ba-4cbb-be46-a8ceb3c8630a/untitled.mov

**Comment by flobarreto** [comment]
Miki this are library issues that are out of scope of profile

**Comment by decentralandmiguel** [comment]
Ok, don't problem! You know where I can leave this feedback? thanks!

**Comment by LautaroPetaccio** [comment]
Hi Miki, we would need to either create a specific button for this or change the library. I would close this issue and wait for the new UI library.

**Comment by LautaroPetaccio** [comment]
Closing it as we won't fix it.
