### ISSUE TITLE
Unnamed not guest

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#137]
When I enter to the profile as un Unnamed. I have 2 problems that we can solve.

Navbar dropdown have to say Unnamed now it says guest
![image.png](https://images.zenhubusercontent.com/64d100d037a41802ee2a6fe8/43fdd32c-6d7c-41e0-8b8c-bdc98d22b4a7)

The empty state is not correct. This is the design proposal. I think we are using the empty state when we see a public profile, not a private profile of an unnamed.
![image.png](https://images.zenhubusercontent.com/64d100d037a41802ee2a6fe8/07c49faf-ca71-4c12-8bf1-8f8c0f503bc9)
This is the one we are using.
![image.png](https://images.zenhubusercontent.com/64d100d037a41802ee2a6fe8/785b9ea2-c731-458f-b433-13e774eda9a7)

**Comment by LautaroPetaccio** [comment]
Hi Miki, we can't change the Unnamed wording in the user menu at the moment. We can do a re-design of it in the future and change it everywhere while checking all dApps to see what name they're using.
We'll fix the issue with the user not having equipped collectibles though.
