### ISSUE TITLE
Unnamed add friend

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#139]
When I sign in with an Unnamed I send a friend request and I can't complete that goal.
https://images.zenhubusercontent.com/660762354/2e193a25-c2bb-4648-8b7c-e6e3de981186/screen_recording_2023_08_08_at_09_46_27.mov

**Comment by LautaroPetaccio** [comment]
Is this happening with all users that you want to unfriend?

**Comment by decentralandmiguel** [comment]
This was not when I want to unfriend is when I want to be friend.

**Comment by LautaroPetaccio** [comment]
Sorry, befriend. Is it happening with all the users that you want to befriend?
