### ISSUE TITLE
Fetch and store friends using the Matrix-clieent

### ISSUE THREAD

**Issue by flobarreto** [decentraland/profile#14]
Fetch and store friends using the matrix client(https://github.com/decentraland/matrix-client.)
    1. Create the social reducer to store the amount of friends the user has.
    2. Create the social actions to store the amount of friends the user has.
    3. Create the social sagas to fetch the amount of friends the user has.
    4. Set up and understand how the **Social client** works.

**Comment by LautaroPetaccio** [comment]
Duplicate.
