### ISSUE TITLE
Image hover

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#143]
When I am hovering the image I see the address. I think is not the behavior that user are expecting I will avoid it.
![image.png](https://images.zenhubusercontent.com/64d100d037a41802ee2a6fe8/62258dda-5bfc-40be-92ae-7274e588cba2)

**Comment by LautaroPetaccio** [comment]
Hi Miki, to remove this we need to modify the global Profile component. If you think that this could make an important change to the user experience, we can take it into consideration, if not, we'll close it.

**Comment by decentralandmiguel** [comment]
I think is really strange to hover the image and to have a long number that the majority of the people that are not crypto savys could not no.

**Comment by LautaroPetaccio** [comment]
Closing it as we won't fix it.
