### ISSUE TITLE
www addressId

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#145]
In the list of use cases, it stated, "As a logged-in or logged-out user, I can navigate to another user’s profile by typing the user’s address in the browser. (www.profile.decentraland.zone/accounts/addressId)"

However, if I use 'www.' in the URL, I can't input the addressID. If I omit it, I can. This is really confusing. I believe the same URL should work the same way, regardless of whether 'www.' is included or not."

**Comment by LautaroPetaccio** [comment]
Hi Miki, we're not using `www` in any of our dApps, this is usually due to `market`, `profile` or other dApps being sub-domains of the original domain. If you go to `https://www.mail.google.com/` it won't work either.
The test case had `www` as a typo.
