### ISSUE TITLE
Mutual friends error

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#146]
When I visited the "flor" profile I saw that I have "Chorizo" In common. But when I go to see Chorizo's profile I don't have mutuals. 
https://images.zenhubusercontent.com/660762354/1c0871a9-37a4-49c9-bd90-fd9c0651f711/screen_recording_2023_08_08_at_11_33_08.mov

**Comment by LautaroPetaccio** [comment]
Would you mind trying to reproduce this issue? It seems that this could be caused by the social service issue that was fixed.

**Comment by decentralandmiguel** [comment]
its ok, we can solve it.
