### ISSUE TITLE
(Private Profile) Change wording of the empty state

### ISSUE THREAD

**Issue by meyaradcl** [decentraland/profile#165]
When I see my own profile and I don't have any equipped collectible wearable the title of the empty state should be:
**_"You don't have any collectible wearables yet."_** (instead of [username]'s doesn't have...)

![Screen Shot 2023-08-08 at 18.36.01.png](https://images.zenhubusercontent.com/63fd1ae1036e7c0512e19f1d/164afe39-4571-4f55-b532-687267c0e37e)

**Comment by flobarreto** [comment]
Hi! I'm seeing my account without wearables like this, have you switched between accounts to see this message?

![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/74d9d67b-ca85-4b8d-9ae9-e760b8e6111e)
