### ISSUE TITLE
(Friends List) Show profile pictures and names instead of wallet addresses

### ISSUE THREAD

**Issue by meyaradcl** [decentraland/profile#167]
It's very hard to identify people without the profile pictures and the display names. 
Also the UI looks broken since addresses overlap with the buttons.

![Screen Shot 2023-08-09 at 11.46.34.png](https://images.zenhubusercontent.com/63fd1ae1036e7c0512e19f1d/6347ce7e-1b16-4e57-8dae-891055b43f54)

This should be very similar to what we have for saved items:
![image.png](https://images.zenhubusercontent.com/63fd1ae1036e7c0512e19f1d/92d975ec-1107-4f0e-b0f1-92f4734b37d3)

**Comment by LautaroPetaccio** [comment]
Hi @meyara92 ! The modal works exactly as it works in the Favorites modal. Your friends in zone must have a name and a profile in order to see them.
We'll shorten the button to prevent the items from being to close.
