### ISSUE TITLE
Mobile Nav Bar

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#173]
Do you think we can put the balance of the user next to the profile pic. It feels like a broken UI to have it under.

![image.png](https://images.zenhubusercontent.com/64d100d037a41802ee2a6fe8/b8bb444f-f252-4805-8787-9b5fb327470a)

**Comment by LautaroPetaccio** [comment]
Hi Miki, this is how it's as of today on all dApps on Mobile. We'll out-scope it and fix it later for all dApps.

**Comment by LautaroPetaccio** [comment]
Closing it as we won't fix it.
