### ISSUE TITLE
Twitter Preview Image

### ISSUE THREAD

**Issue by meyaradcl** [decentraland/profile#194]
(This is an enhancement)
Is it possible to add an image preview to the Twitter post?

![Screen Shot 2023-08-11 at 15.07.09.png](https://images.zenhubusercontent.com/63fd1ae1036e7c0512e19f1d/98b6f14a-54f2-4a24-a00f-30c8c2121655)

There are many options:

- A dynamic picture of the avatar
- A static image like the DCL logo maybe?

**Comment by LautaroPetaccio** [comment]
Hi Mel! This doesn't seem to be possible. What is possible, but can be kind of difficult is to have meta tags on the site that, when accessing or inspecting a link to a profile, could generate an image of the profile that twitter or any other site or application can use. Something similar to what it's used when we share a Marketplace item through the web.
