### ISSUE TITLE
Worlds button in unnamed profiles are disabled

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#199]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBam9CIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--17b9fa65a2e23054a288ab16ced716e9c5411628/image.png)

**Comment by LautaroPetaccio** [comment]
Hi Miki! Does the unnamed user has worlds?

**Comment by decentralandmiguel** [comment]
Unnamed users could have a name because they buy it in the marketplace and activate a world but I think it will be a really strange use case.

**Comment by LautaroPetaccio** [comment]
Closing it as we're disabling the worlds button when the user does not have worlds.
