### ISSUE TITLE
Add Open Graph metadata to the profile site

### ISSUE THREAD

**Issue by LautaroPetaccio** [decentraland/profile#224]
In order to improve the information that is shown in social networks and in search engines, perform complete the following tasks:
- Create a `OpenGrahProfileRoute` class [using this as an example](https://dcl.tools/ops/rollouts-site/-/blob/master/workers/rollouts-site/routes/types/OpenGraphItemRoute.ts) that should fetch the profile of the user from catalyst and build the title and metadata tags.
- Configure [the rollouts sites](https://dcl.tools/ops/rollouts-site/-/blob/master/workers/rollouts-site/rollouts-site-with-routes.ts#L41-67) file so when an instance of the route created before is requested, it builds it.
- Configure the [domains file](https://github.com/decentraland/definitions/blob/main/src/domains.ts#L101-L127) so when the site is loaded, the route class is executed.

**Comment by juanmahidalgo** [comment]
Done!! this is live, closing the issue
