### ISSUE TITLE
Unnamed issue when looking for a name that does not exist

### ISSUE THREAD

**Issue by fzavalia** [decentraland/profile#247]
For example, if I look for `RandomName` 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVdLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fe79374b83d9ef2eb062f46e51229c4744991e4d/Screenshot%202023-09-11%20at%2017.52.16.png)

Which does not exist in Sepolia.

It will show an `Unnamed` profile:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWFLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--75db2b1421465d7a9c28998e684dfc0229f88587/image.png)

With the address and friends of my currently connected wallet.

**Comment by fzavalia** [comment]
The url locally is `http://localhost:5173/accounts/RandomName`

**Comment by fzavalia** [comment]
But if I search for `http://localhost:5173/accounts/asfbasfbafb` I get the NotFound page

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbW1MIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bf84e082160cfe2a17148fabbd724e0f19f734d5/Screenshot%202023-09-11%20at%2023.28.29.png)

🤔

**Comment by LautaroPetaccio** [comment]
This is fixed by the URL redirection.
