### ISSUE TITLE
Filters toggle

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#281]
Filters toggle have to be on the same side, have to be consistent with the other ones. Toggle have to be on the right like "smart" filter. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0V1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e418a6eea5f5bc535bc2b7b25b3ad6d24b7b6a4/image.png)

**Comment by LautaroPetaccio** [comment]
Hi @decentralandmiguel! These filters are the same filters as the ones in the Marketplace, I wouldn't change it at the moment.

**Comment by LautaroPetaccio** [comment]
Closing it as we won't be doing it.
