### ISSUE TITLE
Avatar Interaction

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#99]
* What is happening?
    * When I interact with the avatar I can move the avatar in a vertical way an is not the same type of interaction that we can do in world.
* What should happen?
    * Avoid rotating the avatar in the Y axis only in the X

![image.png](https://images.zenhubusercontent.com/64d100d037a41802ee2a6fe8/56ffe44d-deed-4752-92ec-77214b62f0da)

**Comment by LautaroPetaccio** [comment]
I'm writing this as an enhancement as this would imply modifying the Wearable Preview.
